"""add salon working hours and staff leaves

Revision ID: 723e82f47761
Revises: 3af1b24aa9d6
Create Date: 2026-09-02 19:34:13.140102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723e82f47761'
down_revision: Union[str, Sequence[str], None] = '3af1b24aa9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salon_working_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salon_id', 'day_of_week', name='uq_salon_working_hours_day')
    )
    op.create_index(op.f('ix_salon_working_hours_id'), 'salon_working_hours', ['id'], unique=False)
    op.create_index(op.f('ix_salon_working_hours_salon_id'), 'salon_working_hours', ['salon_id'], unique=False)
    op.create_table('staff_leaves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_leaves_id'), 'staff_leaves', ['id'], unique=False)
    op.create_index(op.f('ix_staff_leaves_staff_id'), 'staff_leaves', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_leaves_staff_id'), table_name='staff_leaves')
    op.drop_index(op.f('ix_staff_leaves_id'), table_name='staff_leaves')
    op.drop_table('staff_leaves')
    op.drop_index(op.f('ix_salon_working_hours_salon_id'), table_name='salon_working_hours')
    op.drop_index(op.f('ix_salon_working_hours_id'), table_name='salon_working_hours')
    op.drop_table('salon_working_hours')
    # ### end Alembic commands ###
