"""add staff to bookings

Revision ID: 76ffb0bbf938
Revises: a580926897fe
Create Date: 2026-09-02 11:45:53.254581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ffb0bbf938'
down_revision: Union[str, Sequence[str], None] = 'a580926897fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('staff_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_bookings_staff_id'), 'bookings', ['staff_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'users', ['staff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_staff_id'), table_name='bookings')
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'staff_id')
    # ### end Alembic commands ###
