"""add salon to users

Revision ID: c3205168ea8c
Revises: fc21609bac78
Create Date: 2026-09-01 21:40:40.160360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3205168ea8c'
down_revision: Union[str, Sequence[str], None] = 'fc21609bac78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'salons', ['salon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'salon_id')
    # ### end Alembic commands ###
